/* eslint-disable */
/* global WebImporter */

/**
 * Transformer: WKND site cleanup
 * Purpose: Remove non-authorable content from AEM Core Components pages
 * Applies to: wknd.site (all templates)
 * Tested: /us/en.html (homepage)
 * Generated: 2026-02-27
 *
 * SELECTORS EXTRACTED FROM:
 * - Captured DOM during migration workflow (migration-work/cleaned.html)
 * - AEM Core Components markup (cmp-* classes)
 * - Experience fragments (header/footer)
 */

const TransformHook = {
  beforeTransform: 'beforeTransform',
  afterTransform: 'afterTransform',
};

export default function transform(hookName, element, payload) {
  if (hookName === TransformHook.beforeTransform) {
    // Remove header experience fragment (not authorable per-page)
    // EXTRACTED: <header class="experiencefragment cmp-experiencefragment--header">
    WebImporter.DOMUtils.remove(element, [
      'header.experiencefragment',
    ]);

    // Remove footer experience fragment (not authorable per-page)
    // EXTRACTED: <footer class="experiencefragment cmp-experiencefragment--footer">
    WebImporter.DOMUtils.remove(element, [
      'footer.experiencefragment',
    ]);

    // Remove carousel UI controls (generated by JS, not authorable)
    // EXTRACTED: <div class="cmp-carousel__actions"> with prev/next buttons
    // EXTRACTED: <ol class="cmp-carousel__indicators"> with dot indicators
    WebImporter.DOMUtils.remove(element, [
      '.cmp-carousel__actions',
      '.cmp-carousel__indicators',
    ]);

    // Remove separator/divider elements (decorative, not authorable)
    // EXTRACTED: <div class="separator ..."><div class="cmp-separator"><hr></div></div>
    WebImporter.DOMUtils.remove(element, [
      '.separator',
    ]);
  }

  if (hookName === TransformHook.afterTransform) {
    // Remove AEM-specific data attributes (data-cmp-*, data-cmp-data-layer-*)
    // EXTRACTED: Various data-cmp-* attributes on AEM components
    element.querySelectorAll('*').forEach((el) => {
      const attrs = Array.from(el.attributes);
      attrs.forEach((attr) => {
        if (attr.name.startsWith('data-cmp')) {
          el.removeAttribute(attr.name);
        }
      });
    });

    // Remove remaining non-content elements
    WebImporter.DOMUtils.remove(element, [
      'noscript',
      'link',
      'meta',
    ]);
  }
}
